### ISSUE TITLE
Provide examples of latitude and longitude forma

### ISSUE THREAD

**Issue by jsiegenthaler** [JoshBello/homebridge-hue-daylight-sync#2]
Hi

Lat and Long can be represented in various formats: degrees, minutes, seconds, or digital degrees, etc.

Your Readme does not state what format is required. 
Could you please update the Readme to provide a real world example (eg for London UK) to help readers understand what should be configured.

Thanks

**Comment by JoshBello** [comment]
Great point, have added clarification: 

- `latitude` Your geographical decimal degrees latitude (e.g. London - 51.5072)
- `longitude` Your geographical decimal degrees longitude (e.g. London - 0.1276)
